/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type { Context } from './context'
import type { Note } from '@prisma/client'

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Application: {
    // root type
    id?: string | null // ID
    name?: string | null // String
    publicKey?: NexusGenRootTypes['JWK'] | null // JWK
  }
  JWK: {
    // root type
    alg?: string | null // String
    crv?: string | null // String
    d?: string | null // String
    dp?: string | null // String
    dq?: string | null // String
    e?: string | null // String
    ext?: string | null // String
    k?: string | null // String
    key_ops?: string | null // String
    kid?: string | null // String
    kty?: string | null // String
    n?: string | null // String
    p?: string | null // String
    q?: string | null // String
    qi?: string | null // String
    use?: string | null // String
    x?: string | null // String
    x5t256?: string | null // String
    x5u?: string | null // String
    y?: string | null // String
  }
  Mutation: {}
  Note: Note
  Query: {}
  User: {
    // root type
    email: string // String!
    hmacSigningKey?: NexusGenRootTypes['JWK'] | null // JWK
    id?: string | null // ID
    name?: string | null // String
  }
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Application: {
    // field return type
    id: string | null // ID
    name: string | null // String
    publicKey: NexusGenRootTypes['JWK'] | null // JWK
  }
  JWK: {
    // field return type
    alg: string | null // String
    crv: string | null // String
    d: string | null // String
    dp: string | null // String
    dq: string | null // String
    e: string | null // String
    ext: string | null // String
    k: string | null // String
    key_ops: string | null // String
    kid: string | null // String
    kty: string | null // String
    n: string | null // String
    p: string | null // String
    q: string | null // String
    qi: string | null // String
    use: string | null // String
    x: string | null // String
    x5t256: string | null // String
    x5u: string | null // String
    y: string | null // String
  }
  Mutation: {
    // field return type
    createNote: NexusGenRootTypes['Note'] // Note!
    editNote: NexusGenRootTypes['Note'] // Note!
  }
  Note: {
    // field return type
    author: NexusGenRootTypes['User'] // User!
    content: string | null // String
    id: string | null // ID
    title: string // String!
  }
  Query: {
    // field return type
    application: NexusGenRootTypes['Application'] // Application!
    note: NexusGenRootTypes['Note'] | null // Note
    notes: NexusGenRootTypes['Note'][] // [Note!]!
  }
  User: {
    // field return type
    email: string // String!
    hmacSigningKey: NexusGenRootTypes['JWK'] | null // JWK
    id: string | null // ID
    name: string | null // String
  }
}

export interface NexusGenFieldTypeNames {
  Application: {
    // field return type name
    id: 'ID'
    name: 'String'
    publicKey: 'JWK'
  }
  JWK: {
    // field return type name
    alg: 'String'
    crv: 'String'
    d: 'String'
    dp: 'String'
    dq: 'String'
    e: 'String'
    ext: 'String'
    k: 'String'
    key_ops: 'String'
    kid: 'String'
    kty: 'String'
    n: 'String'
    p: 'String'
    q: 'String'
    qi: 'String'
    use: 'String'
    x: 'String'
    x5t256: 'String'
    x5u: 'String'
    y: 'String'
  }
  Mutation: {
    // field return type name
    createNote: 'Note'
    editNote: 'Note'
  }
  Note: {
    // field return type name
    author: 'User'
    content: 'String'
    id: 'ID'
    title: 'String'
  }
  Query: {
    // field return type name
    application: 'Application'
    note: 'Note'
    notes: 'Note'
  }
  User: {
    // field return type name
    email: 'String'
    hmacSigningKey: 'JWK'
    id: 'ID'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createNote: {
      // args
      content?: string | null // String
      title: string // String!
    }
    editNote: {
      // args
      content?: string | null // String
      id: string // String!
    }
  }
  Query: {
    note: {
      // args
      id: string // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects

export type NexusGenInputNames = never

export type NexusGenEnumNames = never

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames = keyof NexusGenScalars

export type NexusGenUnionNames = never

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never

export type NexusGenAbstractsUsingStrategyResolveType = never

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  fieldTypeNames: NexusGenFieldTypeNames
  allTypes: NexusGenAllTypes
  typeInterfaces: NexusGenTypeInterfaces
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames']
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames']
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
  abstractTypeMembers: NexusGenAbstractTypeMembers
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType
  features: NexusGenFeaturesConfig
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string,
  > {}
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string,
  > {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
